In [33]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

In [34]:
random.seed(42)
np.random.seed(42)

In [35]:
categories = ["Electronics","Fashion","Books","Home","Grocery"]
payment_methods = ["UPI","Credit Card","Debit Card","Cash on Delivery","Net Banking"]
regions = ["North","South","East","West"]

In [36]:
orders = []

In [37]:
start_date = datetime(2025,1,1)
end_date = datetime(2026,12,31)

In [38]:
for order_id in range(1,101): #generates number 1 to 100
   quantity = random.randint(1,5)
   price = random.randint(200,5000)
   sales = quantity * price
   random_days = random.randint(0,(end_date-start_date).days)
   order_date = start_date + timedelta(days=random_days)
   order = {"Order_ID": order_id,
            "Order_Date": order_date,
            #"Category": random.choice(categories),
            #"Region": random.choice(regions),
            "Payment_Method": random.choice(payment_methods),
            "Quantity":quantity
   }
   orders.append(order)  #Take the current order dictionary , add to list

In [11]:
orders

[{'Order_ID': 1,
  'Order_Date': datetime.datetime(2025, 10, 9, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 404,
  'Sales': 404},
 {'Order_ID': 2,
  'Order_Date': datetime.datetime(2025, 3, 31, 0, 0),
  'Category': 'Grocery',
  'Region': 'West',
  'Payment_Method': 'UPI',
  'Quantity': 1,
  'Unit_Price': 4667,
  'Sales': 4667},
 {'Order_ID': 3,
  'Order_Date': datetime.datetime(2025, 8, 12, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 1,
  'Unit_Price': 967,
  'Sales': 967},
 {'Order_ID': 4,
  'Order_Date': datetime.datetime(2026, 3, 6, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Net Banking',
  'Quantity': 2,
  'Unit_Price': 4664,
  'Sales': 9328},
 {'Order_ID': 5,
  'Order_Date': datetime.datetime(2025, 6, 13, 0, 0),
  'Category': 'Home',
  'Region': 'East',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 253,
  'Sales': 759},
 {'Order_ID': 6,
  'Order_Date': datetime.datetime(2025, 12, 11, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 2,
  'Unit_Price': 1963,
  'Sales': 3926},
 {'Order_ID': 7,
  'Order_Date': datetime.datetime(2025, 12, 19, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'UPI',
  'Quantity': 1,
  'Unit_Price': 3140,
  'Sales': 3140},
 {'Order_ID': 8,
  'Order_Date': datetime.datetime(2025, 5, 8, 0, 0),
  'Category': 'Home',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 4,
  'Unit_Price': 4592,
  'Sales': 18368},
 {'Order_ID': 9,
  'Order_Date': datetime.datetime(2026, 8, 15, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'UPI',
  'Quantity': 3,
  'Unit_Price': 3162,
  'Sales': 9486},
 {'Order_ID': 10,
  'Order_Date': datetime.datetime(2025, 3, 23, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 2,
  'Unit_Price': 2570,
  'Sales': 5140},
 {'Order_ID': 11,
  'Order_Date': datetime.datetime(2026, 10, 13, 0, 0),
  'Category': 'Books',
  'Region': 'South',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 3914,
  'Sales': 11742},
 {'Order_ID': 12,
  'Order_Date': datetime.datetime(2026, 11, 18, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 1916,
  'Sales': 5748},
 {'Order_ID': 13,
  'Order_Date': datetime.datetime(2025, 9, 8, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 2,
  'Unit_Price': 4575,
  'Sales': 9150},
 {'Order_ID': 14,
  'Order_Date': datetime.datetime(2025, 8, 13, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 4762,
  'Sales': 14286},
 {'Order_ID': 15,
  'Order_Date': datetime.datetime(2026, 2, 15, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 2784,
  'Sales': 2784},
 {'Order_ID': 16,
  'Order_Date': datetime.datetime(2025, 8, 6, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 5,
  'Unit_Price': 2777,
  'Sales': 13885},
 {'Order_ID': 17,
  'Order_Date': datetime.datetime(2025, 5, 23, 0, 0),
  'Category': 'Fashion',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 2,
  'Unit_Price': 2369,
  'Sales': 4738},
 {'Order_ID': 18,
  'Order_Date': datetime.datetime(2026, 2, 13, 0, 0),
  'Category': 'Books',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 4,
  'Unit_Price': 4980,
  'Sales': 19920},
 {'Order_ID': 19,
  'Order_Date': datetime.datetime(2025, 4, 4, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Credit Card',
  'Quantity': 5,
  'Unit_Price': 4242,
  'Sales': 21210},
 {'Order_ID': 20,
  'Order_Date': datetime.datetime(2026, 9, 3, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 2,
  'Unit_Price': 3658,
  'Sales': 7316},
 {'Order_ID': 21,
  'Order_Date': datetime.datetime(2026, 6, 26, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'UPI',
  'Quantity': 5,
  'Unit_Price': 4034,
  'Sales': 20170},
 {'Order_ID': 22,
  'Order_Date': datetime.datetime(2026, 10, 19, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 5,
  'Unit_Price': 2385,
  'Sales': 11925},
 {'Order_ID': 23,
  'Order_Date': datetime.datetime(2026, 4, 10, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 4,
  'Unit_Price': 1495,
  'Sales': 5980},
 {'Order_ID': 24,
  'Order_Date': datetime.datetime(2025, 4, 19, 0, 0),
  'Category': 'Books',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 2,
  'Unit_Price': 4358,
  'Sales': 8716},
 {'Order_ID': 25,
  'Order_Date': datetime.datetime(2026, 7, 7, 0, 0),
  'Category': 'Grocery',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 1523,
  'Sales': 4569},
 {'Order_ID': 26,
  'Order_Date': datetime.datetime(2025, 1, 20, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 4202,
  'Sales': 12606},
 {'Order_ID': 27,
  'Order_Date': datetime.datetime(2025, 9, 4, 0, 0),
  'Category': 'Grocery',
  'Region': 'North',
  'Payment_Method': 'UPI',
  'Quantity': 2,
  'Unit_Price': 674,
  'Sales': 1348},
 {'Order_ID': 28,
  'Order_Date': datetime.datetime(2026, 6, 30, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 766,
  'Sales': 3064},
 {'Order_ID': 29,
  'Order_Date': datetime.datetime(2025, 9, 29, 0, 0),
  'Category': 'Grocery',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 5,
  'Unit_Price': 1552,
  'Sales': 7760},
 {'Order_ID': 30,
  'Order_Date': datetime.datetime(2025, 11, 16, 0, 0),
  'Category': 'Home',
  'Region': 'East',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 5,
  'Unit_Price': 1847,
  'Sales': 9235},
 {'Order_ID': 31,
  'Order_Date': datetime.datetime(2025, 5, 4, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'UPI',
  'Quantity': 5,
  'Unit_Price': 3898,
  'Sales': 19490},
 {'Order_ID': 32,
  'Order_Date': datetime.datetime(2026, 8, 26, 0, 0),
  'Category': 'Grocery',
  'Region': 'South',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 372,
  'Sales': 1116},
 {'Order_ID': 33,
  'Order_Date': datetime.datetime(2025, 3, 14, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'UPI',
  'Quantity': 2,
  'Unit_Price': 258,
  'Sales': 516},
 {'Order_ID': 34,
  'Order_Date': datetime.datetime(2025, 3, 14, 0, 0),
  'Category': 'Grocery',
  'Region': 'South',
  'Payment_Method': 'Debit Card',
  'Quantity': 1,
  'Unit_Price': 2906,
  'Sales': 2906},
 {'Order_ID': 35,
  'Order_Date': datetime.datetime(2026, 7, 7, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 4,
  'Unit_Price': 1955,
  'Sales': 7820},
 {'Order_ID': 36,
  'Order_Date': datetime.datetime(2025, 7, 14, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 3534,
  'Sales': 14136},
 {'Order_ID': 37,
  'Order_Date': datetime.datetime(2026, 2, 25, 0, 0),
  'Category': 'Home',
  'Region': 'North',
  'Payment_Method': 'UPI',
  'Quantity': 3,
  'Unit_Price': 3669,
  'Sales': 11007},
 {'Order_ID': 38,
  'Order_Date': datetime.datetime(2025, 12, 14, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 3498,
  'Sales': 3498},
 {'Order_ID': 39,
  'Order_Date': datetime.datetime(2026, 4, 5, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 2,
  'Unit_Price': 4593,
  'Sales': 9186},
 {'Order_ID': 40,
  'Order_Date': datetime.datetime(2025, 9, 13, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 3989,
  'Sales': 11967},
 {'Order_ID': 41,
  'Order_Date': datetime.datetime(2026, 10, 30, 0, 0),
  'Category': 'Grocery',
  'Region': 'North',
  'Payment_Method': 'UPI',
  'Quantity': 1,
  'Unit_Price': 614,
  'Sales': 614},
 {'Order_ID': 42,
  'Order_Date': datetime.datetime(2026, 2, 21, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 2,
  'Unit_Price': 1562,
  'Sales': 3124},
 {'Order_ID': 43,
  'Order_Date': datetime.datetime(2025, 6, 18, 0, 0),
  'Category': 'Home',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 680,
  'Sales': 2720},
 {'Order_ID': 44,
  'Order_Date': datetime.datetime(2025, 10, 20, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 3927,
  'Sales': 11781},
 {'Order_ID': 45,
  'Order_Date': datetime.datetime(2025, 8, 11, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 2,
  'Unit_Price': 2630,
  'Sales': 5260},
 {'Order_ID': 46,
  'Order_Date': datetime.datetime(2026, 8, 22, 0, 0),
  'Category': 'Home',
  'Region': 'South',
  'Payment_Method': 'UPI',
  'Quantity': 1,
  'Unit_Price': 610,
  'Sales': 610},
 {'Order_ID': 47,
  'Order_Date': datetime.datetime(2025, 7, 10, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Credit Card',
  'Quantity': 5,
  'Unit_Price': 856,
  'Sales': 4280},
 {'Order_ID': 48,
  'Order_Date': datetime.datetime(2026, 8, 7, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 4,
  'Unit_Price': 1182,
  'Sales': 4728},
 {'Order_ID': 49,
  'Order_Date': datetime.datetime(2026, 11, 5, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'Debit Card',
  'Quantity': 1,
  'Unit_Price': 3634,
  'Sales': 3634},
 {'Order_ID': 50,
  'Order_Date': datetime.datetime(2025, 9, 2, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 2,
  'Unit_Price': 2773,
  'Sales': 5546},
 {'Order_ID': 51,
  'Order_Date': datetime.datetime(2025, 11, 20, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 3,
  'Unit_Price': 3945,
  'Sales': 11835},
 {'Order_ID': 52,
  'Order_Date': datetime.datetime(2025, 4, 13, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Net Banking',
  'Quantity': 5,
  'Unit_Price': 4812,
  'Sales': 24060},
 {'Order_ID': 53,
  'Order_Date': datetime.datetime(2025, 12, 24, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 1285,
  'Sales': 3855},
 {'Order_ID': 54,
  'Order_Date': datetime.datetime(2026, 3, 25, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 1492,
  'Sales': 4476},
 {'Order_ID': 55,
  'Order_Date': datetime.datetime(2026, 11, 15, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'UPI',
  'Quantity': 5,
  'Unit_Price': 264,
  'Sales': 1320},
 {'Order_ID': 56,
  'Order_Date': datetime.datetime(2025, 4, 29, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Debit Card',
  'Quantity': 2,
  'Unit_Price': 2366,
  'Sales': 4732},
 {'Order_ID': 57,
  'Order_Date': datetime.datetime(2025, 12, 18, 0, 0),
  'Category': 'Fashion',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 1925,
  'Sales': 5775},
 {'Order_ID': 58,
  'Order_Date': datetime.datetime(2025, 2, 22, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 4,
  'Unit_Price': 2257,
  'Sales': 9028},
 {'Order_ID': 59,
  'Order_Date': datetime.datetime(2025, 12, 8, 0, 0),
  'Category': 'Fashion',
  'Region': 'East',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 229,
  'Sales': 229},
 {'Order_ID': 60,
  'Order_Date': datetime.datetime(2026, 12, 24, 0, 0),
  'Category': 'Home',
  'Region': 'North',
  'Payment_Method': 'UPI',
  'Quantity': 4,
  'Unit_Price': 4719,
  'Sales': 18876},
 {'Order_ID': 61,
  'Order_Date': datetime.datetime(2026, 7, 13, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 1,
  'Unit_Price': 1421,
  'Sales': 1421},
 {'Order_ID': 62,
  'Order_Date': datetime.datetime(2026, 3, 17, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 5,
  'Unit_Price': 1413,
  'Sales': 7065},
 {'Order_ID': 63,
  'Order_Date': datetime.datetime(2026, 1, 2, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'UPI',
  'Quantity': 3,
  'Unit_Price': 526,
  'Sales': 1578},
 {'Order_ID': 64,
  'Order_Date': datetime.datetime(2026, 2, 21, 0, 0),
  'Category': 'Grocery',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 4786,
  'Sales': 14358},
 {'Order_ID': 65,
  'Order_Date': datetime.datetime(2026, 2, 27, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Debit Card',
  'Quantity': 2,
  'Unit_Price': 1650,
  'Sales': 3300},
 {'Order_ID': 66,
  'Order_Date': datetime.datetime(2025, 10, 1, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 2232,
  'Sales': 8928},
 {'Order_ID': 67,
  'Order_Date': datetime.datetime(2025, 8, 16, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 1,
  'Unit_Price': 4055,
  'Sales': 4055},
 {'Order_ID': 68,
  'Order_Date': datetime.datetime(2025, 8, 17, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 3,
  'Unit_Price': 2064,
  'Sales': 6192},
 {'Order_ID': 69,
  'Order_Date': datetime.datetime(2025, 3, 13, 0, 0),
  'Category': 'Books',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 2482,
  'Sales': 7446},
 {'Order_ID': 70,
  'Order_Date': datetime.datetime(2025, 12, 6, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 4,
  'Unit_Price': 4592,
  'Sales': 18368},
 {'Order_ID': 71,
  'Order_Date': datetime.datetime(2025, 9, 29, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 2,
  'Unit_Price': 4956,
  'Sales': 9912},
 {'Order_ID': 72,
  'Order_Date': datetime.datetime(2025, 11, 18, 0, 0),
  'Category': 'Home',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 3031,
  'Sales': 12124},
 {'Order_ID': 73,
  'Order_Date': datetime.datetime(2025, 9, 18, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'UPI',
  'Quantity': 5,
  'Unit_Price': 1757,
  'Sales': 8785},
 {'Order_ID': 74,
  'Order_Date': datetime.datetime(2026, 12, 5, 0, 0),
  'Category': 'Fashion',
  'Region': 'East',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 5,
  'Unit_Price': 4610,
  'Sales': 23050},
 {'Order_ID': 75,
  'Order_Date': datetime.datetime(2026, 10, 1, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 1,
  'Unit_Price': 2904,
  'Sales': 2904},
 {'Order_ID': 76,
  'Order_Date': datetime.datetime(2026, 11, 14, 0, 0),
  'Category': 'Home',
  'Region': 'East',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 5,
  'Unit_Price': 2733,
  'Sales': 13665},
 {'Order_ID': 77,
  'Order_Date': datetime.datetime(2025, 5, 11, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 3,
  'Unit_Price': 4741,
  'Sales': 14223},
 {'Order_ID': 78,
  'Order_Date': datetime.datetime(2025, 11, 5, 0, 0),
  'Category': 'Home',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 2,
  'Unit_Price': 4862,
  'Sales': 9724},
 {'Order_ID': 79,
  'Order_Date': datetime.datetime(2026, 3, 17, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 3,
  'Unit_Price': 1921,
  'Sales': 5763},
 {'Order_ID': 80,
  'Order_Date': datetime.datetime(2026, 11, 23, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 4,
  'Unit_Price': 3822,
  'Sales': 15288},
 {'Order_ID': 81,
  'Order_Date': datetime.datetime(2026, 6, 12, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'UPI',
  'Quantity': 1,
  'Unit_Price': 2524,
  'Sales': 2524},
 {'Order_ID': 82,
  'Order_Date': datetime.datetime(2025, 8, 19, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'UPI',
  'Quantity': 2,
  'Unit_Price': 2742,
  'Sales': 5484},
 {'Order_ID': 83,
  'Order_Date': datetime.datetime(2026, 5, 2, 0, 0),
  'Category': 'Grocery',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 1,
  'Unit_Price': 2205,
  'Sales': 2205},
 {'Order_ID': 84,
  'Order_Date': datetime.datetime(2025, 7, 19, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 4915,
  'Sales': 19660},
 {'Order_ID': 85,
  'Order_Date': datetime.datetime(2026, 11, 3, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 2,
  'Unit_Price': 1408,
  'Sales': 2816},
 {'Order_ID': 86,
  'Order_Date': datetime.datetime(2026, 12, 14, 0, 0),
  'Category': 'Grocery',
  'Region': 'West',
  'Payment_Method': 'UPI',
  'Quantity': 2,
  'Unit_Price': 1640,
  'Sales': 3280},
 {'Order_ID': 87,
  'Order_Date': datetime.datetime(2025, 5, 5, 0, 0),
  'Category': 'Home',
  'Region': 'South',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 5,
  'Unit_Price': 2241,
  'Sales': 11205},
 {'Order_ID': 88,
  'Order_Date': datetime.datetime(2026, 9, 2, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'Net Banking',
  'Quantity': 5,
  'Unit_Price': 4778,
  'Sales': 23890},
 {'Order_ID': 89,
  'Order_Date': datetime.datetime(2026, 7, 16, 0, 0),
  'Category': 'Home',
  'Region': 'South',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 5,
  'Unit_Price': 3695,
  'Sales': 18475},
 {'Order_ID': 90,
  'Order_Date': datetime.datetime(2025, 9, 11, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 4,
  'Unit_Price': 2323,
  'Sales': 9292},
 {'Order_ID': 91,
  'Order_Date': datetime.datetime(2025, 3, 21, 0, 0),
  'Category': 'Books',
  'Region': 'South',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 3803,
  'Sales': 11409},
 {'Order_ID': 92,
  'Order_Date': datetime.datetime(2026, 7, 8, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 2819,
  'Sales': 8457},
 {'Order_ID': 93,
  'Order_Date': datetime.datetime(2026, 12, 12, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'UPI',
  'Quantity': 2,
  'Unit_Price': 3337,
  'Sales': 6674},
 {'Order_ID': 94,
  'Order_Date': datetime.datetime(2025, 12, 5, 0, 0),
  'Category': 'Grocery',
  'Region': 'West',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 3539,
  'Sales': 14156},
 {'Order_ID': 95,
  'Order_Date': datetime.datetime(2026, 3, 7, 0, 0),
  'Category': 'Home',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 1,
  'Unit_Price': 1894,
  'Sales': 1894},
 {'Order_ID': 96,
  'Order_Date': datetime.datetime(2025, 1, 7, 0, 0),
  'Category': 'Books',
  'Region': 'East',

In [39]:
df = pd.DataFrame(orders)
df.head()

   Order_ID Order_Date Payment_Method  Quantity
0         1 2025-10-09    Credit Card         1
1         2 2025-04-15    Net Banking         2
2         3 2025-02-02            UPI         1
3         4 2025-08-27    Net Banking         1
4         5 2026-07-29    Credit Card         5

In [40]:
df.tail()

    Order_ID Order_Date Payment_Method  Quantity
95        96 2026-12-09    Credit Card         1
96        97 2026-01-14    Net Banking         5
97        98 2026-03-17    Credit Card         5
98        99 2026-01-09            UPI         1
99       100 2026-11-30    Credit Card         3

In [41]:
df.shape

(100, 4)

In [42]:
df.columns

Index(['Order_ID', 'Order_Date', 'Payment_Method', 'Quantity'], dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Order_Date      100 non-null    datetime64[us]
 2   Category        100 non-null    str
 3   Region          100 non-null    str
 4   Payment_Method  100 non-null    str
 5   Quantity        100 non-null    int64
 6   Unit_Price      100 non-null    int64
 7   Sales           100 non-null    int64
dtypes: datetime64[us](1), int64(4), str(3)
memory usage: 6.4 KB

In [43]:
df.describe()

         Order_ID           Order_Date    Quantity
count  100.000000                  100  100.000000
mean    50.500000  2025-12-01 22:04:48    3.120000
min      1.000000  2025-01-04 00:00:00    1.000000
25%     25.750000  2025-06-03 12:00:00    2.000000
50%     50.500000  2025-11-15 12:00:00    3.000000
75%     75.250000  2026-05-31 00:00:00    5.000000
max    100.000000  2026-12-09 00:00:00    5.000000
std     29.011492                  NaN    1.539251

Generate tables for Customers & Product

In [44]:
num_customers = 100
customers = pd.DataFrame({
    "customer_id":range(1,num_customers+1),
    "customer_name":[f"Customer_{i}" for i in range(1, num_customers + 1)],
    "city":np.random.choice(["Bangalore","Delhi","Chennai","Mumbai"],num_customers),
    "signup_date":pd.to_datetime("2024-01-01")  + pd.to_timedelta(np.random.randint(0,365,num_customers),unit="D")
})

In [45]:
num_products = 50
products = pd.DataFrame({
    "product_id":range(1,num_products+1),
    "product_name":[f"Product_{i}" for i in range(1,num_products+1)],
    "category": np.random.choice(["Electronics","Clothing","Home","Books"],num_products),
    "price": np.random.randint(100,5000,num_products)
})

In [46]:
df["customer_id"] = np.random.randint(1, num_customers + 1, len(df))
df["product_id"] = np.random.randint(1, num_products + 1, len(df))
df.head()

   Order_ID Order_Date Payment_Method  Quantity  customer_id  product_id
0         1 2025-10-09    Credit Card         1           99          32
1         2 2025-04-15    Net Banking         2            7          23
2         3 2025-02-02            UPI         1           16          33
3         4 2025-08-27    Net Banking         1           90           3
4         5 2026-07-29    Credit Card         5           60          18

In [48]:
df.to_csv("../data/raw/amazon_retail_data.csv",index=False)

In [49]:
customers.to_csv("../data/raw/customers.csv", index=False)

In [50]:
products.to_csv("../data/raw/products.csv", index=False)

In [51]:
df = df.merge(customers, on="customer_id", how="left")
df = df.merge(products, on="product_id", how="left")

In [52]:
df["Sales"] = df["Quantity"] * df["price"]
df.head()

,Order_ID,Order_Date,Payment_Method,Quantity,customer_id,product_id,customer_name,city,signup_date,product_name,category,price,Sales
0,1,2025-10-09,Credit Card,1,99,32,Customer_99,Delhi,2024-02-13,Product_32,Books,1894,1894
1,2,2025-04-15,Net Banking,2,7,23,Customer_7,Bangalore,2024-12-16,Product_23,Books,297,594
2,3,2025-02-02,UPI,1,16,33,Customer_16,Bangalore,2024-08-24,Product_33,Home,759,759
3,4,2025-08-27,Net Banking,1,90,3,Customer_90,Delhi,2024-10-10,Product_3,Home,3099,3099
4,5,2026-07-29,Credit Card,5,60,18,Customer_60,Bangalore,2024-09-13,Product_18,Electronics,4596,22980

In [30]:
df.drop(columns=["Unit_Price"], inplace=True, errors="ignore")
df.head()

,Order_ID,Order_Date,Category,Region,Payment_Method,Quantity,Sales,customer_id,product_id,customer_name,city,signp_date,product_name,category,price
0,1,2025-10-09,Fashion,South,Credit Card,1,1317,65,46,Customer_65,Mumbai,2024-01-10,Product_46,Home,1317
1,2,2025-03-31,Grocery,West,UPI,1,832,86,35,Customer_86,Mumbai,2024-06-26,Product_35,Electronics,832
2,3,2025-08-12,Fashion,North,Net Banking,1,3014,17,6,Customer_17,Delhi,2024-02-27,Product_6,Home,3014
3,4,2026-03-06,Fashion,West,Net Banking,2,1634,71,18,Customer_71,Delhi,2024-08-10,Product_18,Electronics,817
4,5,2025-06-13,Home,East,Debit Card,3,7278,89,5,Customer_89,Mumbai,2024-06-27,Product_5,Clothing,2426

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Order_Date      100 non-null    datetime64[us]
 2   Payment_Method  100 non-null    str
 3   Quantity        100 non-null    int64
 4   customer_id     100 non-null    int32
 5   product_id      100 non-null    int32
 6   customer_name   100 non-null    str
 7   city            100 non-null    str
 8   signup_date     100 non-null    datetime64[us]
 9   product_name    100 non-null    str
 10  category        100 non-null    str
 11  price           100 non-null    int32
 12  Sales           100 non-null    int64
dtypes: datetime64[us](2), int32(3), int64(3), str(5)
memory usage: 9.1 KB

Generate tables for Customers & Product

In [21]:
orders["customer_id"] = np.random.randint(1,num_customers+1,len(orders))
orders["product_id"]  = np.random.randint(1,num_products+1,len(orders))

TypeError: list indices must be integers or slices, not str