In [1]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

In [2]:
random.seed(42)
np.random.seed(42)

In [3]:
categories = ["Electronics","Fashion","Books","Home","Grocery"]
payment_methods = ["UPI","Credit Card","Debit Card","Cash on Delivery","Net Banking"]
regions = ["North","South","East","West"]

In [19]:
orders = []

In [20]:
start_date = datetime(2025,1,1)
end_date = datetime(2026,12,31)

In [21]:
for order_id in range(1,101): #generates number 1 to 100
   quantity = random.randint(1,5)
   price = random.randint(200,5000)
   sales = quantity * price
   random_days = random.randint(0,(end_date-start_date).days)
   order_date = start_date + timedelta(days=random_days)
   order = {"Order_ID": order_id,
            "Order_Date": order_date,
            "Category": random.choice(categories),
            "Region": random.choice(regions),
            "Payment_Method": random.choice(payment_methods),
            "Quantity":quantity,
            "Unit_Price":price,
            "Sales":sales
   }
   orders.append(order)  #Take the current order dictionary , add to list

In [22]:
orders

[{'Order_ID': 1,
  'Order_Date': datetime.datetime(2026, 10, 13, 0, 0),
  'Category': 'Home',
  'Region': 'East',
  'Payment_Method': 'Debit Card',
  'Quantity': 4,
  'Unit_Price': 556,
  'Sales': 2224},
 {'Order_ID': 2,
  'Order_Date': datetime.datetime(2025, 3, 11, 0, 0),
  'Category': 'Books',
  'Region': 'South',
  'Payment_Method': 'UPI',
  'Quantity': 1,
  'Unit_Price': 3125,
  'Sales': 3125},
 {'Order_ID': 3,
  'Order_Date': datetime.datetime(2025, 5, 17, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 5,
  'Unit_Price': 2923,
  'Sales': 14615},
 {'Order_ID': 4,
  'Order_Date': datetime.datetime(2026, 12, 3, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 1634,
  'Sales': 4902},
 {'Order_ID': 5,
  'Order_Date': datetime.datetime(2026, 4, 14, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'Credit Card',
  'Quantity': 2,
  'Unit_Price': 716,
  'Sales': 1432},
 {'Order_ID': 6,
  'Order_Date': datetime.datetime(2025, 2, 12, 0, 0),
  'Category': 'Books',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 1,
  'Unit_Price': 1834,
  'Sales': 1834},
 {'Order_ID': 7,
  'Order_Date': datetime.datetime(2026, 4, 30, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'Credit Card',
  'Quantity': 4,
  'Unit_Price': 4648,
  'Sales': 18592},
 {'Order_ID': 8,
  'Order_Date': datetime.datetime(2025, 2, 18, 0, 0),
  'Category': 'Books',
  'Region': 'East',
  'Payment_Method': 'UPI',
  'Quantity': 3,
  'Unit_Price': 3124,
  'Sales': 9372},
 {'Order_ID': 9,
  'Order_Date': datetime.datetime(2026, 2, 14, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 3779,
  'Sales': 11337},
 {'Order_ID': 10,
  'Order_Date': datetime.datetime(2026, 12, 10, 0, 0),
  'Category': 'Home',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 2,
  'Unit_Price': 4264,
  'Sales': 8528},
 {'Order_ID': 11,
  'Order_Date': datetime.datetime(2026, 3, 11, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 876,
  'Sales': 2628},
 {'Order_ID': 12,
  'Order_Date': datetime.datetime(2025, 10, 28, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'UPI',
  'Quantity': 2,
  'Unit_Price': 4668,
  'Sales': 9336},
 {'Order_ID': 13,
  'Order_Date': datetime.datetime(2025, 11, 10, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 2621,
  'Sales': 7863},
 {'Order_ID': 14,
  'Order_Date': datetime.datetime(2026, 4, 3, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 4,
  'Unit_Price': 3079,
  'Sales': 12316},
 {'Order_ID': 15,
  'Order_Date': datetime.datetime(2026, 10, 17, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 2449,
  'Sales': 9796},
 {'Order_ID': 16,
  'Order_Date': datetime.datetime(2026, 11, 27, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 4403,
  'Sales': 13209},
 {'Order_ID': 17,
  'Order_Date': datetime.datetime(2025, 2, 5, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'Credit Card',
  'Quantity': 5,
  'Unit_Price': 3789,
  'Sales': 18945},
 {'Order_ID': 18,
  'Order_Date': datetime.datetime(2026, 1, 28, 0, 0),
  'Category': 'Grocery',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 3166,
  'Sales': 9498},
 {'Order_ID': 19,
  'Order_Date': datetime.datetime(2026, 1, 15, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'UPI',
  'Quantity': 2,
  'Unit_Price': 3885,
  'Sales': 7770},
 {'Order_ID': 20,
  'Order_Date': datetime.datetime(2026, 6, 27, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 5,
  'Unit_Price': 1327,
  'Sales': 6635},
 {'Order_ID': 21,
  'Order_Date': datetime.datetime(2025, 4, 27, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 3,
  'Unit_Price': 2244,
  'Sales': 6732},
 {'Order_ID': 22,
  'Order_Date': datetime.datetime(2026, 7, 30, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'Debit Card',
  'Quantity': 5,
  'Unit_Price': 3370,
  'Sales': 16850},
 {'Order_ID': 23,
  'Order_Date': datetime.datetime(2026, 9, 19, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 4,
  'Unit_Price': 1957,
  'Sales': 7828},
 {'Order_ID': 24,
  'Order_Date': datetime.datetime(2025, 3, 17, 0, 0),
  'Category': 'Home',
  'Region': 'South',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 1,
  'Unit_Price': 1311,
  'Sales': 1311},
 {'Order_ID': 25,
  'Order_Date': datetime.datetime(2026, 11, 15, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 1,
  'Unit_Price': 2818,
  'Sales': 2818},
 {'Order_ID': 26,
  'Order_Date': datetime.datetime(2025, 11, 4, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'Debit Card',
  'Quantity': 5,
  'Unit_Price': 2578,
  'Sales': 12890},
 {'Order_ID': 27,
  'Order_Date': datetime.datetime(2025, 5, 5, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 5,
  'Unit_Price': 2036,
  'Sales': 10180},
 {'Order_ID': 28,
  'Order_Date': datetime.datetime(2026, 1, 5, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 415,
  'Sales': 1660},
 {'Order_ID': 29,
  'Order_Date': datetime.datetime(2026, 9, 19, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 5,
  'Unit_Price': 1263,
  'Sales': 6315},
 {'Order_ID': 30,
  'Order_Date': datetime.datetime(2026, 6, 23, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Net Banking',
  'Quantity': 4,
  'Unit_Price': 4121,
  'Sales': 16484},
 {'Order_ID': 31,
  'Order_Date': datetime.datetime(2025, 11, 21, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 1,
  'Unit_Price': 1226,
  'Sales': 1226},
 {'Order_ID': 32,
  'Order_Date': datetime.datetime(2025, 5, 12, 0, 0),
  'Category': 'Grocery',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 5,
  'Unit_Price': 3022,
  'Sales': 15110},
 {'Order_ID': 33,
  'Order_Date': datetime.datetime(2025, 2, 26, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Debit Card',
  'Quantity': 4,
  'Unit_Price': 4319,
  'Sales': 17276},
 {'Order_ID': 34,
  'Order_Date': datetime.datetime(2025, 11, 27, 0, 0),
  'Category': 'Fashion',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 2,
  'Unit_Price': 1526,
  'Sales': 3052},
 {'Order_ID': 35,
  'Order_Date': datetime.datetime(2025, 9, 14, 0, 0),
  'Category': 'Fashion',
  'Region': 'East',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 846,
  'Sales': 2538},
 {'Order_ID': 36,
  'Order_Date': datetime.datetime(2025, 4, 6, 0, 0),
  'Category': 'Grocery',
  'Region': 'South',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 4570,
  'Sales': 13710},
 {'Order_ID': 37,
  'Order_Date': datetime.datetime(2025, 6, 25, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 5,
  'Unit_Price': 1463,
  'Sales': 7315},
 {'Order_ID': 38,
  'Order_Date': datetime.datetime(2025, 3, 25, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 432,
  'Sales': 432},
 {'Order_ID': 39,
  'Order_Date': datetime.datetime(2026, 9, 25, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Net Banking',
  'Quantity': 5,
  'Unit_Price': 3612,
  'Sales': 18060},
 {'Order_ID': 40,
  'Order_Date': datetime.datetime(2026, 5, 10, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 2674,
  'Sales': 8022},
 {'Order_ID': 41,
  'Order_Date': datetime.datetime(2026, 12, 7, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 797,
  'Sales': 3188},
 {'Order_ID': 42,
  'Order_Date': datetime.datetime(2026, 4, 21, 0, 0),
  'Category': 'Fashion',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 4,
  'Unit_Price': 4166,
  'Sales': 16664},
 {'Order_ID': 43,
  'Order_Date': datetime.datetime(2025, 11, 23, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 2,
  'Unit_Price': 2760,
  'Sales': 5520},
 {'Order_ID': 44,
  'Order_Date': datetime.datetime(2026, 7, 30, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 4418,
  'Sales': 13254},
 {'Order_ID': 45,
  'Order_Date': datetime.datetime(2025, 10, 1, 0, 0),
  'Category': 'Home',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 4,
  'Unit_Price': 1203,
  'Sales': 4812},
 {'Order_ID': 46,
  'Order_Date': datetime.datetime(2025, 10, 25, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 614,
  'Sales': 614},
 {'Order_ID': 47,
  'Order_Date': datetime.datetime(2026, 8, 15, 0, 0),
  'Category': 'Books',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 2,
  'Unit_Price': 2882,
  'Sales': 5764},
 {'Order_ID': 48,
  'Order_Date': datetime.datetime(2026, 4, 24, 0, 0),
  'Category': 'Home',
  'Region': 'East',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 4416,
  'Sales': 17664},
 {'Order_ID': 49,
  'Order_Date': datetime.datetime(2026, 2, 7, 0, 0),
  'Category': 'Grocery',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 937,
  'Sales': 937},
 {'Order_ID': 50,
  'Order_Date': datetime.datetime(2025, 12, 28, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 2,
  'Unit_Price': 4978,
  'Sales': 9956},
 {'Order_ID': 51,
  'Order_Date': datetime.datetime(2025, 10, 20, 0, 0),
  'Category': 'Grocery',
  'Region': 'North',
  'Payment_Method': 'UPI',
  'Quantity': 4,
  'Unit_Price': 4055,
  'Sales': 16220},
 {'Order_ID': 52,
  'Order_Date': datetime.datetime(2025, 9, 28, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 4,
  'Unit_Price': 1297,
  'Sales': 5188},
 {'Order_ID': 53,
  'Order_Date': datetime.datetime(2025, 2, 22, 0, 0),
  'Category': 'Grocery',
  'Region': 'South',
  'Payment_Method': 'Debit Card',
  'Quantity': 1,
  'Unit_Price': 3481,
  'Sales': 3481},
 {'Order_ID': 54,
  'Order_Date': datetime.datetime(2025, 3, 17, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Net Banking',
  'Quantity': 5,
  'Unit_Price': 2564,
  'Sales': 12820},
 {'Order_ID': 55,
  'Order_Date': datetime.datetime(2025, 5, 12, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 1173,
  'Sales': 3519},
 {'Order_ID': 56,
  'Order_Date': datetime.datetime(2026, 1, 10, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 4769,
  'Sales': 14307},
 {'Order_ID': 57,
  'Order_Date': datetime.datetime(2026, 5, 28, 0, 0),
  'Category': 'Electronics',
  'Region': 'North',
  'Payment_Method': 'UPI',
  'Quantity': 5,
  'Unit_Price': 3488,
  'Sales': 17440},
 {'Order_ID': 58,
  'Order_Date': datetime.datetime(2026, 5, 1, 0, 0),
  'Category': 'Grocery',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 2,
  'Unit_Price': 2928,
  'Sales': 5856},
 {'Order_ID': 59,
  'Order_Date': datetime.datetime(2025, 5, 24, 0, 0),
  'Category': 'Books',
  'Region': 'East',
  'Payment_Method': 'Credit Card',
  'Quantity': 5,
  'Unit_Price': 4423,
  'Sales': 22115},
 {'Order_ID': 60,
  'Order_Date': datetime.datetime(2026, 8, 31, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'Net Banking',
  'Quantity': 4,
  'Unit_Price': 2651,
  'Sales': 10604},
 {'Order_ID': 61,
  'Order_Date': datetime.datetime(2025, 1, 18, 0, 0),
  'Category': 'Books',
  'Region': 'East',
  'Payment_Method': 'UPI',
  'Quantity': 3,
  'Unit_Price': 4090,
  'Sales': 12270},
 {'Order_ID': 62,
  'Order_Date': datetime.datetime(2025, 11, 12, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 4,
  'Unit_Price': 4981,
  'Sales': 19924},
 {'Order_ID': 63,
  'Order_Date': datetime.datetime(2025, 8, 22, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 5,
  'Unit_Price': 4931,
  'Sales': 24655},
 {'Order_ID': 64,
  'Order_Date': datetime.datetime(2025, 6, 1, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'Net Banking',
  'Quantity': 5,
  'Unit_Price': 3314,
  'Sales': 16570},
 {'Order_ID': 65,
  'Order_Date': datetime.datetime(2025, 1, 20, 0, 0),
  'Category': 'Home',
  'Region': 'East',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 1,
  'Unit_Price': 1762,
  'Sales': 1762},
 {'Order_ID': 66,
  'Order_Date': datetime.datetime(2026, 12, 9, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Net Banking',
  'Quantity': 2,
  'Unit_Price': 3582,
  'Sales': 7164},
 {'Order_ID': 67,
  'Order_Date': datetime.datetime(2025, 3, 5, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'Net Banking',
  'Quantity': 5,
  'Unit_Price': 4063,
  'Sales': 20315},
 {'Order_ID': 68,
  'Order_Date': datetime.datetime(2026, 6, 23, 0, 0),
  'Category': 'Home',
  'Region': 'East',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 4118,
  'Sales': 12354},
 {'Order_ID': 69,
  'Order_Date': datetime.datetime(2025, 12, 17, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'Debit Card',
  'Quantity': 4,
  'Unit_Price': 4567,
  'Sales': 18268},
 {'Order_ID': 70,
  'Order_Date': datetime.datetime(2025, 7, 16, 0, 0),
  'Category': 'Fashion',
  'Region': 'East',
  'Payment_Method': 'Net Banking',
  'Quantity': 5,
  'Unit_Price': 4166,
  'Sales': 20830},
 {'Order_ID': 71,
  'Order_Date': datetime.datetime(2025, 11, 1, 0, 0),
  'Category': 'Books',
  'Region': 'South',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 3,
  'Unit_Price': 2042,
  'Sales': 6126},
 {'Order_ID': 72,
  'Order_Date': datetime.datetime(2025, 12, 24, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 4130,
  'Sales': 12390},
 {'Order_ID': 73,
  'Order_Date': datetime.datetime(2026, 11, 24, 0, 0),
  'Category': 'Grocery',
  'Region': 'West',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 1,
  'Unit_Price': 4897,
  'Sales': 4897},
 {'Order_ID': 74,
  'Order_Date': datetime.datetime(2025, 10, 25, 0, 0),
  'Category': 'Electronics',
  'Region': 'East',
  'Payment_Method': 'UPI',
  'Quantity': 3,
  'Unit_Price': 1399,
  'Sales': 4197},
 {'Order_ID': 75,
  'Order_Date': datetime.datetime(2026, 11, 3, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 3823,
  'Sales': 11469},
 {'Order_ID': 76,
  'Order_Date': datetime.datetime(2025, 10, 5, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'Credit Card',
  'Quantity': 2,
  'Unit_Price': 4612,
  'Sales': 9224},
 {'Order_ID': 77,
  'Order_Date': datetime.datetime(2025, 9, 6, 0, 0),
  'Category': 'Electronics',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 2160,
  'Sales': 2160},
 {'Order_ID': 78,
  'Order_Date': datetime.datetime(2026, 2, 28, 0, 0),
  'Category': 'Books',
  'Region': 'West',
  'Payment_Method': 'UPI',
  'Quantity': 1,
  'Unit_Price': 1020,
  'Sales': 1020},
 {'Order_ID': 79,
  'Order_Date': datetime.datetime(2026, 7, 18, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 2,
  'Unit_Price': 242,
  'Sales': 484},
 {'Order_ID': 80,
  'Order_Date': datetime.datetime(2025, 10, 22, 0, 0),
  'Category': 'Books',
  'Region': 'East',
  'Payment_Method': 'UPI',
  'Quantity': 4,
  'Unit_Price': 1833,
  'Sales': 7332},
 {'Order_ID': 81,
  'Order_Date': datetime.datetime(2025, 8, 26, 0, 0),
  'Category': 'Grocery',
  'Region': 'North',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 4903,
  'Sales': 4903},
 {'Order_ID': 82,
  'Order_Date': datetime.datetime(2025, 2, 7, 0, 0),
  'Category': 'Home',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 4,
  'Unit_Price': 1640,
  'Sales': 6560},
 {'Order_ID': 83,
  'Order_Date': datetime.datetime(2025, 1, 10, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 506,
  'Sales': 1518},
 {'Order_ID': 84,
  'Order_Date': datetime.datetime(2026, 10, 19, 0, 0),
  'Category': 'Grocery',
  'Region': 'West',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 3922,
  'Sales': 11766},
 {'Order_ID': 85,
  'Order_Date': datetime.datetime(2025, 10, 7, 0, 0),
  'Category': 'Fashion',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 5,
  'Unit_Price': 4034,
  'Sales': 20170},
 {'Order_ID': 86,
  'Order_Date': datetime.datetime(2026, 10, 26, 0, 0),
  'Category': 'Books',
  'Region': 'South',
  'Payment_Method': 'UPI',
  'Quantity': 2,
  'Unit_Price': 3959,
  'Sales': 7918},
 {'Order_ID': 87,
  'Order_Date': datetime.datetime(2026, 8, 5, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'Net Banking',
  'Quantity': 3,
  'Unit_Price': 2616,
  'Sales': 7848},
 {'Order_ID': 88,
  'Order_Date': datetime.datetime(2026, 6, 12, 0, 0),
  'Category': 'Books',
  'Region': 'North',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 3703,
  'Sales': 14812},
 {'Order_ID': 89,
  'Order_Date': datetime.datetime(2025, 5, 24, 0, 0),
  'Category': 'Home',
  'Region': 'East',
  'Payment_Method': 'Credit Card',
  'Quantity': 1,
  'Unit_Price': 1713,
  'Sales': 1713},
 {'Order_ID': 90,
  'Order_Date': datetime.datetime(2026, 1, 28, 0, 0),
  'Category': 'Fashion',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 1,
  'Unit_Price': 2336,
  'Sales': 2336},
 {'Order_ID': 91,
  'Order_Date': datetime.datetime(2026, 8, 20, 0, 0),
  'Category': 'Grocery',
  'Region': 'North',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 2673,
  'Sales': 8019},
 {'Order_ID': 92,
  'Order_Date': datetime.datetime(2025, 3, 5, 0, 0),
  'Category': 'Electronics',
  'Region': 'West',
  'Payment_Method': 'Debit Card',
  'Quantity': 3,
  'Unit_Price': 2135,
  'Sales': 6405},
 {'Order_ID': 93,
  'Order_Date': datetime.datetime(2026, 12, 4, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'UPI',
  'Quantity': 2,
  'Unit_Price': 3521,
  'Sales': 7042},
 {'Order_ID': 94,
  'Order_Date': datetime.datetime(2026, 9, 22, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',
  'Payment_Method': 'Credit Card',
  'Quantity': 3,
  'Unit_Price': 3210,
  'Sales': 9630},
 {'Order_ID': 95,
  'Order_Date': datetime.datetime(2026, 4, 11, 0, 0),
  'Category': 'Grocery',
  'Region': 'East',
  'Payment_Method': 'Cash on Delivery',
  'Quantity': 4,
  'Unit_Price': 1454,
  'Sales': 5816},
 {'Order_ID': 96,
  'Order_Date': datetime.datetime(2026, 7, 5, 0, 0),
  'Category': 'Fashion',
  'Region': 'South',

In [23]:
df = pd.DataFrame(orders)
df.head()

,Order_ID,Order_Date,Category,Region,Payment_Method,Quantity,Unit_Price,Sales
0,1,2026-10-13,Home,East,Debit Card,4,556,2224
1,2,2025-03-11,Books,South,UPI,1,3125,3125
2,3,2025-05-17,Electronics,East,Net Banking,5,2923,14615
3,4,2026-12-03,Home,West,Credit Card,3,1634,4902
4,5,2026-04-14,Electronics,East,Credit Card,2,716,1432

In [24]:
df.tail()

,Order_ID,Order_Date,Category,Region,Payment_Method,Quantity,Unit_Price,Sales
95,96,2026-07-05,Fashion,South,Net Banking,5,4057,20285
96,97,2026-04-03,Grocery,East,UPI,1,4504,4504
97,98,2025-03-05,Grocery,South,Net Banking,5,1119,5595
98,99,2025-06-18,Books,West,UPI,5,1427,7135
99,100,2026-05-16,Electronics,West,UPI,2,4977,9954

In [25]:
df.shape

(100, 8)

In [26]:
df.columns

Index(['Order_ID', 'Order_Date', 'Category', 'Region', 'Payment_Method',
       'Quantity', 'Unit_Price', 'Sales'],
      dtype='str')

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Order_Date      100 non-null    datetime64[us]
 2   Category        100 non-null    str
 3   Region          100 non-null    str
 4   Payment_Method  100 non-null    str
 5   Quantity        100 non-null    int64
 6   Unit_Price      100 non-null    int64
 7   Sales           100 non-null    int64
dtypes: datetime64[us](1), int64(4), str(3)
memory usage: 6.4 KB

In [28]:
df.describe()

         Order_ID           Order_Date    Quantity   Unit_Price         Sales
count  100.000000                  100  100.000000   100.000000    100.000000
mean    50.500000  2025-12-30 20:52:48    3.140000  2848.100000   9110.290000
min      1.000000  2025-01-10 00:00:00    1.000000   242.000000    432.000000
25%     25.750000  2025-06-13 18:00:00    2.000000  1607.000000   4427.250000
50%     50.500000  2025-12-26 00:00:00    3.000000  2925.500000   7855.500000
75%     75.250000  2026-06-29 00:00:00    4.000000  4069.750000  13220.250000
max    100.000000  2026-12-10 00:00:00    5.000000  4981.000000  24655.000000
std     29.011492                  NaN    1.370836  1379.528133   6079.135278

In [29]:
df.to_csv("../data/raw/amazon_retail_data.csv",index=False)